-- Crear tabla profiles para usuarios/admin
create table public.profiles (
  id uuid references auth.users not null,
  role text check (role in ('admin', 'client')) default 'client',
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Configurar RLS para profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Crear tabla services
create table public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price text,
  features text[], -- Array de características
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar RLS para services
alter table public.services enable row level security;
create policy "Services are viewable by everyone." on services for select using (true);
create policy "Only admins can insert/update services." on services for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Insertar servicios iniciales por defecto (opcional)
insert into public.services (name, description, price, features) values
('Inventario de PCs', 'Control absoluto del hardware y software de tu institución.', '$2,500/mes', '{"Reportes automáticos","Alertas de mantenimiento","Gestión de licencias"}'),
('Control de Ingreso/Egreso', 'Gestión segura del flujo de alumnos y personal docente.', '$3,000/mes', '{"Asistencia en tiempo real","Notificaciones a tutores","Integración con molinetes"}'),
('Gestión Académica', 'Plataforma centralizada para notas, asistencias y comunicados.', '$5,000/mes', '{"Portal para padres","Boletines digitales","Calendario escolar"}'),
('Hosting y Servidores', 'Alojamiento web optimizado para plataformas educativas.', '$1,500/mes', '{"Alta disponibilidad","Backups diarios","Soporte técnico 24/7"}');

-- Crear tabla requests (solicitudes de contratación)
create table public.requests (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users, -- Permitiremos nulo por ahora para visitantes anónimos
  service_id bigint references services,
  contact_name text not null,
  contact_email text not null,
  contact_phone text,
  message text,
  status text check (status in ('pending', 'contacted', 'resolved')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar RLS para requests
alter table public.requests enable row level security;
create policy "Anyone can insert a request." on requests for insert with check (true);
create policy "Users can view their own requests." on requests for select using (auth.uid() = user_id);
create policy "Admins can view and update all requests." on requests for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
