-- ══════════════════════════════════════════════════════════════════
-- Landing Page — Unificación de schema con el proyecto Supabase
-- compartido (mismo proyecto que usa "Agenda Educativa").
--
-- Ejecutar en el SQL Editor de Supabase (o via `supabase db push`
-- una vez logueado con `supabase login` / `supabase link`).
--
-- Qué hace:
--   1. Reutiliza public.profiles / public.schools de Agenda Educativa
--      como única fuente de verdad de identidad/tenant (NO crea una
--      tabla profiles propia, NO crea un segundo trigger
--      on_auth_user_created).
--   2. Agrega el rol 'client' al enum de profiles.role para los
--      usuarios que se registran desde Landing Page (leads/clientes
--      que todavía no son un "school" tenant en Agenda Educativa).
--   3. Crea un schema Postgres nuevo `landing` con las tablas propias
--      de este proyecto (catálogo de servicios y solicitudes de
--      contratación) para no ensuciar `public`.
--
-- IMPORTANTE — paso manual post-migración:
--   Supabase por defecto solo expone el schema `public` vía la API
--   (PostgREST). Para que `supabase.schema('landing').from(...)`
--   funcione desde el cliente hay que agregar `landing` a los
--   schemas expuestos:
--     Dashboard → Project Settings → Data API → Exposed schemas
--     → agregar "landing" a la lista (además de "public") → Save.
--   Sin este paso, cualquier query a landing.* devuelve 404/permiso
--   denegado aunque la migración se haya corrido bien.
-- ══════════════════════════════════════════════════════════════════

-- ─── 1. Rol 'client' para profiles compartido ───────────────────────
-- No se toca la tabla ni el trigger de Agenda Educativa: solo se
-- extiende el CHECK constraint de role para agregar el valor que
-- necesita Landing Page. Se re-declaran todos los roles existentes
-- para no perder ninguno (teacher/director/admin/superadmin/student/
-- tutor ya en uso por Agenda Educativa).
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('teacher', 'director', 'admin', 'superadmin', 'student', 'tutor', 'client'));

-- ─── 2. Schema propio de Landing Page ───────────────────────────────
CREATE SCHEMA IF NOT EXISTS landing;

GRANT USAGE ON SCHEMA landing TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA landing GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA landing GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- ─── 3. Catálogo de servicios (los 5 SaaS que ofrece NMF) ───────────
CREATE TABLE IF NOT EXISTS landing.services (
  id          bigint generated by default as identity primary key,
  name        text NOT NULL,
  description text,
  price       text,
  features    text[],
  is_active   boolean DEFAULT true,
  created_at  timestamptz DEFAULT now()
);

GRANT ALL ON landing.services TO anon, authenticated, service_role;

ALTER TABLE landing.services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "landing_services_select_all" ON landing.services;
CREATE POLICY "landing_services_select_all" ON landing.services
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "landing_services_admin_write" ON landing.services;
CREATE POLICY "landing_services_admin_write" ON landing.services
  FOR ALL TO authenticated
  USING (public.get_user_role() IN ('admin', 'superadmin'))
  WITH CHECK (public.get_user_role() IN ('admin', 'superadmin'));

-- Seed inicial: solo si la tabla está vacía (idempotente, sin depender
-- de una unique key sobre "name").
INSERT INTO landing.services (name, description, price, features)
SELECT * FROM (VALUES
  ('Inventario de PCs', 'Control absoluto del hardware y software de tu institución.', '$2,500/mes', ARRAY['Reportes automáticos','Alertas de mantenimiento','Gestión de licencias']),
  ('Control de Ingreso/Egreso', 'Gestión segura del flujo de alumnos y personal docente.', '$3,000/mes', ARRAY['Asistencia en tiempo real','Notificaciones a tutores','Integración con molinetes']),
  ('Gestión Académica', 'Plataforma centralizada para notas, asistencias y comunicados.', '$5,000/mes', ARRAY['Portal para padres','Boletines digitales','Calendario escolar']),
  ('Hosting y Servidores', 'Alojamiento web optimizado para plataformas educativas.', '$1,500/mes', ARRAY['Alta disponibilidad','Backups diarios','Soporte técnico 24/7'])
) AS seed(name, description, price, features)
WHERE NOT EXISTS (SELECT 1 FROM landing.services);

-- ─── 4. Solicitudes de contratación (leads) ─────────────────────────
CREATE TABLE IF NOT EXISTS landing.requests (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  service_id    bigint REFERENCES landing.services(id),
  contact_name  text NOT NULL,
  contact_email text NOT NULL,
  contact_phone text,
  message       text,
  status        text CHECK (status IN ('pending', 'contacted', 'resolved')) DEFAULT 'pending',
  created_at    timestamptz DEFAULT now()
);

GRANT ALL ON landing.requests TO anon, authenticated, service_role;

ALTER TABLE landing.requests ENABLE ROW LEVEL SECURITY;

-- Cualquiera (incluso visitante anónimo) puede crear una solicitud
DROP POLICY IF EXISTS "landing_requests_insert_anyone" ON landing.requests;
CREATE POLICY "landing_requests_insert_anyone" ON landing.requests
  FOR INSERT WITH CHECK (true);

-- Un usuario logueado ve sus propias solicitudes (por user_id si se
-- seteó, o por email si la mandó como visitante y coincide con su
-- cuenta actual)
DROP POLICY IF EXISTS "landing_requests_select_own" ON landing.requests;
CREATE POLICY "landing_requests_select_own" ON landing.requests
  FOR SELECT TO authenticated
  USING (
    auth.uid() = user_id
    OR contact_email = (auth.jwt() ->> 'email')
  );

-- Admins/superadmins de NMF ven y gestionan todas las solicitudes
DROP POLICY IF EXISTS "landing_requests_admin_all" ON landing.requests;
CREATE POLICY "landing_requests_admin_all" ON landing.requests
  FOR ALL TO authenticated
  USING (public.get_user_role() IN ('admin', 'superadmin'))
  WITH CHECK (public.get_user_role() IN ('admin', 'superadmin'));

-- Recargar caché de PostgREST
NOTIFY pgrst, 'reload schema';
